# Generated by Django 5.2.3 on 2025-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactmessage_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
